tasks:
  - name: Elm tests
    cmd: elm-test
  - name: Elm format validation
    cmd: find . -type f -name '*.elm' | grep -v -e elm-stuff -e '\.elm/' | xargs elm-format --validate
  - name: Elm review
    cmd: elm-review
